### ISSUE TITLE
[Bug] idk

### ISSUE THREAD

**Issue by Sentii** [JsSucks/BetterDiscordApp#301]
Sorry, I don't use GitHub at all.
https://cdn.discordapp.com/attachments/536389434543833098/553708392284160005/2019-03-08_16-19-21.gif
https://cdn.discordapp.com/attachments/536389434543833098/553708390690455552/2019-03-08_16-19-58.gif
(Clicking "Server Discovery" got rid of the "New" notification)

**Comment by satoru8** [comment]
The first one isn't a bug, its just telling you its a new feature. Click it.  
The other part you can fix with this 
```scss

body {
	&:not(.bd-hideButton) {
		.wrapper-1Rf91z {
			padding-top: 50px;
			+ {
				[class*='flex'] {
					border-radius: 0 0 0 5px;
				}
			}
		}
		.platform-osx {
			.wrapper-1Rf91z {
				margin-top: 25px;
			}
		}
	}
}
```
