### ISSUE TITLE
[Bug] Themes are unable to import local files to their stylesheet

### ISSUE THREAD

**Issue by intrnl** [JsSucks/BetterDiscordApp#320]
- [x] Used appropriate template for the issue type
- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and _concisely_ reflects the feature or the bug

**Describe the bug**

Title explains it all, themes are unable to import local files on the theme's directory with relative path.

**To Reproduce**

```
theme/
  background.jpg
  config.json
  index.scss
```
```scss
// index.scss
body {
  background-image: url('./background.jpg');
}
```

**Expected behavior**

The relative path should be transformed into the base64'd version of the file that was pointed at.
```css
body {
  background-image: url(data:image/png;base64,d2h5IGRpZCB5b3UgZXZlbiBib3RoZXIgZGVjb2RpbmcgdGhpcywgaXQncyBwb2ludGxlc3MsIHN0b3AgaXQu);
}
```

**Screenshots**

No screenshots necessary

**System information**

Manjaro Linux 5.0.2, Discord Stable

**Additional context**

plsfix

**Are you willing and able to fix this?**

Perhaps.
